// --------------------------------------------------------------------------------------------------------------------
// <copyright file="ConstructorArgumentValidationTestScenarios{T}.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.CodeGen.ModelObject.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.CodeGen.ModelObject.Recipes
{
    using global::System;
    using global::System.Collections.Generic;

    using OBeautifulCode.Assertion.Recipes;
    using OBeautifulCode.Type.Recipes;

    using static global::System.FormattableString;

    /// <summary>
    /// Specifies various scenarios for constructor argument validation tests.
    /// </summary>
    /// <typeparam name="T">The type of the object being tested.</typeparam>
#if !OBeautifulCodeCodeGenSolution
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.CodeGen.ModelObject.Recipes", "See package version number")]
    internal
#else
    public
#endif
    class ConstructorArgumentValidationTestScenarios<T>
        where T : class
    {
        private readonly object lockScenarios = new object();

        private readonly List<Lazy<ConstructorArgumentValidationTestScenario<T>>> scenarios = new List<Lazy<ConstructorArgumentValidationTestScenario<T>>>();

        /// <summary>
        /// Adds the specified scenario to the list of scenarios.
        /// </summary>
        /// <param name="scenario">The scenario to add.</param>
        /// <returns>
        /// This object.
        /// </returns>
        public ConstructorArgumentValidationTestScenarios<T> AddScenario(
            ConstructorArgumentValidationTestScenario<T> scenario)
        {
            new { scenario }.AsTest().Must().NotBeNull();

            this.AddScenario(() => scenario);

            return this;
        }

        /// <summary>
        /// Adds the specified scenario to the list of scenarios.
        /// </summary>
        /// <param name="scenarioFunc">A func that returns the scenario to add.</param>
        /// <returns>
        /// This object.
        /// </returns>
        public ConstructorArgumentValidationTestScenarios<T> AddScenario(
            Func<ConstructorArgumentValidationTestScenario<T>> scenarioFunc)
        {
            new { scenarioFunc }.AsTest().Must().NotBeNull();

            lock (this.lockScenarios)
            {
                // We are wrapping in a Lazy<> because the code-generated scenarios may
                // throw based on assertions within the model object's constructor.  We want
                // the end-user to have an opportunity to clear-out the scenarios and specify
                // their own (via static constructor on the test class) before the code-generated
                // ones are evaluated and throw.
                var lazyScenario = new Lazy<ConstructorArgumentValidationTestScenario<T>>(scenarioFunc);

                this.scenarios.Add(lazyScenario);
            }

            return this;
        }

        /// <summary>
        /// Adds the specified scenarios to the list of scenarios.
        /// </summary>
        /// <param name="constructorArgumentValidationTestScenarios">The scenarios to add.</param>
        /// <returns>
        /// This object.
        /// </returns>
        public ConstructorArgumentValidationTestScenarios<T> AddScenarios(
            ConstructorArgumentValidationTestScenarios<T> constructorArgumentValidationTestScenarios)
        {
            new { constructorArgumentValidationTestScenarios }.AsTest().Must().NotBeNull();

            lock (this.lockScenarios)
            {
                this.scenarios.AddRange(constructorArgumentValidationTestScenarios.scenarios);
            }

            return this;
        }

        /// <summary>
        /// Removes all scenarios.
        /// </summary>
        /// <returns>
        /// This object.
        /// </returns>
        public ConstructorArgumentValidationTestScenarios<T> RemoveAllScenarios()
        {
            lock (this.lockScenarios)
            {
                this.scenarios.Clear();
            }

            return this;
        }

        /// <summary>
        /// Validates the scenarios and prepares them for testing.
        /// </summary>
        /// <returns>
        /// The validated/prepared scenarios.
        /// </returns>
        public IReadOnlyList<ValidatedConstructorArgumentValidationTestScenario<T>> ValidateAndPrepareForTesting()
        {
            lock (this.lockScenarios)
            {
                var typeCompilableString = typeof(T).ToStringCompilable();

                var becauseNoScenarios = new[]
                {
                    Invariant($"Use a static constructor on your test class to add scenarios by calling {nameof(ConstructorArgumentValidationTestScenarios<object>)}.{nameof(ConstructorArgumentValidationTestScenarios<object>.AddScenario)}(...)."),
                    Invariant($"If the constructor cannot throw, clear all scenarios by calling {nameof(ConstructorArgumentValidationTestScenarios<object>)}.{nameof(ConstructorArgumentValidationTestScenarios<object>.RemoveAllScenarios)}() and add {nameof(ConstructorArgumentValidationTestScenario<object>)}<{typeCompilableString}>.{nameof(ConstructorArgumentValidationTestScenario<object>.ConstructorCannotThrowScenario)}."),
                    Invariant($"If you need to force the consuming unit tests to pass and you'll write your own unit tests, clear all scenarios and then add {nameof(ConstructorArgumentValidationTestScenario<object>)}<{typeCompilableString}>.{nameof(ConstructorArgumentValidationTestScenario<object>.ForceGeneratedTestsToPassAndWriteMyOwnScenario)}."),
                };

                this.scenarios.AsTest(Invariant($"{nameof(ConstructorArgumentValidationTestScenarios<object>)}.{nameof(ConstructorArgumentValidationTestScenarios<object>.scenarios)}")).Must().NotBeEmptyEnumerable(because: string.Join(Environment.NewLine, becauseNoScenarios), applyBecause: ApplyBecause.SuffixedToDefaultMessage);

                var result = new List<ValidatedConstructorArgumentValidationTestScenario<T>>();

                var scenariosCount = this.scenarios.Count;

                for (var x = 0; x < scenariosCount; x++)
                {
                    var scenario = this.scenarios[x].Value;

                    var scenarioNumber = x + 1;

                    var scenarioName = string.IsNullOrWhiteSpace(scenario.Name) ? "<Unnamed Scenario>" : scenario.Name;

                    var scenarioId = Invariant($"{scenarioName} ({nameof(ConstructorArgumentValidationTestScenario<object>)} #{scenarioNumber} of {scenariosCount}):");

                    var validatedScenario = new ValidatedConstructorArgumentValidationTestScenario<T>(
                        scenarioId,
                        scenario.ConstructionFunc,
                        scenario.ExpectedExceptionType,
                        scenario.ExpectedExceptionMessageContains,
                        scenario.ExpectedExceptionMessageEquals);

                    result.Add(validatedScenario);
                }

                return result;
            }
        }
    }
}
