// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SystemUnderTestExpectedStringRepresentation{T}.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.CodeGen.ModelObject.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.CodeGen.ModelObject.Recipes
{
    /// <summary>
    /// An object being tested and its expected string representation.
    /// </summary>
    /// <typeparam name="T">The type of the object being tested.</typeparam>
#if !OBeautifulCodeCodeGenSolution
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.CodeGen.ModelObject.Recipes", "See package version number")]
    internal
#else
    public
#endif
    class SystemUnderTestExpectedStringRepresentation<T>
        where T : class
    {
        /// <summary>
        /// Gets or sets the object being tested.
        /// </summary>
        public T SystemUnderTest { get; set; }

        /// <summary>
        /// Gets or sets the expected string representation.
        /// </summary>
        public string ExpectedStringRepresentation { get; set; }
    }
}
