// --------------------------------------------------------------------------------------------------------------------
// <copyright file="SerializationConfigurationTypes.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   From Naos.Build.Conventions.VisualStudioProjectTemplates - 1.55.45.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Deployment.Core.Test
{
    using System;
    using System.CodeDom.Compiler;
    using System.Diagnostics.CodeAnalysis;
    using Naos.Deployment.Domain;
    using Naos.Deployment.Persistence;
    using OBeautifulCode.Serialization.Bson;
    using OBeautifulCode.Serialization.Json;

    [ExcludeFromCodeCoverage]
    [GeneratedCode("Naos.Build.Conventions.VisualStudioProjectTemplates", "1.55.45")]
    public static class SerializationConfigurationTypes
    {
        public static BsonSerializationConfigurationType BsonSerializationConfigurationType => typeof(DeploymentBsonSerializationConfiguration).ToBsonSerializationConfigurationType();

        public static JsonSerializationConfigurationType JsonSerializationConfigurationType => typeof(NaosDeploymentDomainJsonSerializationConfiguration).ToJsonSerializationConfigurationType();
    }
}