// --------------------------------------------------------------------------------------------------------------------
// <copyright file="MachineMemory.cs" company="Naos Project">
//    Copyright (c) Naos Project 2019. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in Naos.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace Naos.Diagnostics.Recipes
{
    using System.Collections.Generic;

    using Microsoft.VisualBasic.Devices;

    /// <summary>
    /// Uses various methods to get the memory of a machine.
    /// </summary>
#if NaosDiagnosticsRecipes
    public
#else
    [System.CodeDom.Compiler.GeneratedCode("Naos.Diagnostics", "See package version number")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    internal
#endif
    static class MachineMemory
    {
        private const decimal DivideByToGetGb = 1024m * 1024m * 1024m;

        /// <summary>
        /// Gets the total physical memory of this machine in gigabytes.
        /// </summary>
        /// <returns>
        /// The total memory of this machine in gigabytes.
        /// </returns>
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Justification = "Don't want to use a property for this kind of active call.")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Gb", Justification = "Name/spelling is correct.")]
        public static IReadOnlyDictionary<MachineMemoryKind, decimal> GetMachineMemoryInGb()
        {
            // this is only in VisualBasic...
            var computerInfo = new ComputerInfo();
            var result = new Dictionary<MachineMemoryKind, decimal>
                             {
                                 { MachineMemoryKind.TotalPhysical, computerInfo.TotalPhysicalMemory / DivideByToGetGb },
                                 { MachineMemoryKind.AvailablePhysical, computerInfo.AvailablePhysicalMemory / DivideByToGetGb },
                                 { MachineMemoryKind.TotalVirtual, computerInfo.TotalVirtualMemory / DivideByToGetGb },
                                 { MachineMemoryKind.AvailableVirtual, computerInfo.AvailableVirtualMemory / DivideByToGetGb },
                             };

            return result;
        }
    }
}
